### ISSUE TITLE
Use a button

### ISSUE THREAD

**Issue by DetailsMatterM** [DIT112-V19/group-01#12]
As a car-alarm owner, I want the car to provide a hardware interface I can interact with, to be able to use additional functionality

Acceptance criteria: User can give the car input

**Comment by Hlebanja** [comment]
@Gusmuaha @Fredrik93 Hassan, when you add the stop button functionality, please reference this issue and, if you remember it, mark it as closed afterwards.

**Comment by Hlebanja** [comment]
This issue was ambiguous and this has caused a little bit of confusion on it's planning and execution. The issue definition has been clarified - it refers to a hardware interface (probably a button) which the user can press on the car
