### ISSUE TITLE
Implement MP3 shield with speaker

### ISSUE THREAD

**Issue by GeorgeKarageozian** [DIT112-V19/group-01#37]
## Description
As a car-alarm owner, I want to be able to upload alarm sounds and hear the alarm from the speaker of the car.
## Acceptance Criteria
The car can ring different alarm sounds.

**Comment by DetailsMatterM** [comment]
We decided to go for a buzzer as a minimum viable product, in sprint 7 we might implement it still

**Comment by Fredrik93** [comment]
We decided to stay with the buzzer as it was the better option.
