### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by Hlebanja** [DIT112-V19/group-01#43]
## Description
As a car-alarm owner I want to operate the car without bugs. 

## Acceptance Criteria
Travis CI runs checks and doesn't find any bugs

**Comment by Hlebanja** [comment]
This issue has been extended to Sprint 6 and 7.

**Comment by Fredrik93** [comment]
Should have implemented since the beginning, this was addressed in our post mortem section in the group report.
