### ISSUE TITLE
Notice moving objects

### ISSUE THREAD

**Issue by Fredrik93** [DIT112-V19/group-01#7]
As a car-alarm owner, i want the car to be able to recognize people following it, so it will be more difficult to catch it 

Acceptance criteria : User can see that the car is recognizing the user

**Comment by DetailsMatterM** [comment]
Change "notice" to sense
Change text to:
As a car-alarm owner, i want the car to be able to sense movement close to the button to recognize me following it, so it will be more difficult to catch it
